### ISSUE TITLE
Add more target

### ISSUE THREAD

**Issue by kitsuyui** [kitsuyui/go-myip#5]
- [x] Some HTTP/HTTPS endpoints.
- [x] ~resolver.dnscrypt.org~
- [ ] ~whoami.fluffcomputing.com~
- [x] whoami.ultradns.net
- [x] o-o.myaddr.l.google.com

**Comment by kitsuyui** [comment]
#8

**Comment by jedisct1** [comment]
Just a heads up: `resolver.dnscrypt.org` has been replaced with `resolver.00f.net`.

**Comment by kitsuyui** [comment]
@judisct1 Thanks. Does it finally mean `resolver.dnscrypt.org` and `resolver.00f.net` is not usable to detect own IP address, right?

**Comment by jedisct1** [comment]
Correct. They are very useful, but not for that purpose.

**Comment by kitsuyui** [comment]
@jedisct1 Thank you for telling me!
I will remove it from checklist.

**Comment by kitsuyui** [comment]
And `whoami.fluffcomputing.com` is a example domain for https://github.com/pjperez/whoami .
This doesn't suit for my purpose.

So all domains are completed on this issue.
